### ISSUE TITLE
Saving fitted models to disk?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/modelr#10]
One good addition to `fit_with()` would be a .save argument taking a path to a .rds where we would save the dataset, the list of formulas, the fitted models and the additional `...` parameters. When that argument is supplied, we would only refit a model if the data, its formula or the input parameters changed.

In that case we probably need to use `purrr::safely()` to fit the models.

That would be great for models that take hours to fit, especially now that we have rstanarm.

**Comment by lionel-** [comment]
In addition, could we somehow have version control of model revisions...?

**Comment by lionel-** [comment]
This could be a general R package to manage git repo or submodules within a project.

```{r}
repo <- versionr::create("models/disp/", additive = fit_additive)
```

This would create a git repo or submodule in "./models/disp/" and a additive.rds file containing `fit_additive` in the initial commit. Then:

```{r}
versionr::update(repo, additive = fit_additive, full = fit_full)
```

Would update `fit_additive` and create a new commit if the objects differ. In addition it creates full.rds and commit it.

Then `fit_with()` could take either a string of a path or a repo object. Hmm... Or maybe we should have specific modelr repo objects organised around a data frame. These could be ordinary repo objects pointing to a repo containing a `.modelr-data.rds` file. So we'd do something like:

```{r}
repo <- modelr::versionise("models/", mtcars)
repo %>% fit_with(lm, formulas)
```

and

```r
repo %>%
  versionr::subdirectory("disp") %>%
  fit_with(lm, disp_formulas)
```

**Comment by hadley** [comment]
I think this is now clearly outside the scope of modelr - it's a package primarily for teaching the basics of modelling before moving on to the more sophisticated tools provided by @topepo
