### ISSUE TITLE
Allow American spelling of "colour" in geom_ref_line

### ISSUE THREAD

**Issue by brianrice2** [tidyverse/modelr#110]
It would be nice if `geom_ref_line()` could handle the American spelling of "colour" too, like `ggplot2` does.

Example:

``` r
library(tidyverse)
library(modelr)
mtcars %>% 
  ggplot() + 
  geom_point(aes(mpg, hp, color = as.factor(cyl))) +
  geom_ref_line(h = 120, colour = "black", size = 0.5)
```

![](https://i.imgur.com/Xz9OSLy.png)

``` r

mtcars %>% 
  ggplot() + 
  geom_point(aes(mpg, hp, color = as.factor(cyl))) +
  geom_ref_line(h = 120, color = "black", size = 0.5)
#> Error in geom_ref_line(h = 120, color = "black", size = 0.5): unused argument (color = "black")
```

<sup>Created on 2020-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
modelr is now superseded, which means that we'll only perform critical bug fixes needed to keep it on CRAN. Thanks for contributing this idea and my apologies that it took so long to inform you that this package is no longer under development.
