### ISSUE TITLE
Feature request: support for many standard error specifications in add_predictions

### ISSUE THREAD

**Issue by kendonB** [tidyverse/modelr#15]
For example, those in `sandwich` and `multiwayvcov`.

Even better, create a new model object that carries around a vcov matrix, like the lfe::felm object does,
that gets used by `predict`, and `summary`.

**Comment by LaDilettante** [comment]
Does `add_predictions` currently return any kind of standard errors? I couldn't find it.

**Comment by jebyrnes** [comment]
Given that the first variable from any predict function I've encountered is typically the prediction, could this be accomplished with

```
add_predictions <- function (data, model, var = "pred", ...) {
  fit <- as_tibble(stats::predict(model, data, ...))
  names(fit)[1] <- var  
  bind_cols(data, fit)
}
```

This also alleviates some additional problems in that many predict functions require additional arguments, such as `predict.glm()` where you might want `type = "response"`

See the following example:

```
# A Gamma example, from McCullagh & Nelder (1989, pp. 300-2)
library(tidyr)
library(modelr)
library(ggplot2)

clotting <- tibble(
  u = c(5,10,15,20,30,40,60,80,100),
  lot1 = c(118,58,42,35,27,25,21,19,18),
  lot2 = c(69,35,26,21,18,16,13,12,12)) %>%
  gather(lot, value, -u)

mod <- glm(value ~ log(u)*lot, data = clotting, family = Gamma)

fit <- clotting %>%
  data_grid(u=seq_range(u, 100), lot=c("lot1", "lot2")) %>%
  add_predictions(mod, var = "value", type="response", se.fit=TRUE)

ggplot(clotting,
       aes(x=u, y=value, color=lot)) +
  geom_point() +
  geom_line(data = fit) +
  geom_ribbon(data = fit, mapping=aes(ymin = value - 2*se.fit,
                                      ymax = value + 2*se.fit,
                                      group = lot), 
              alpha=0.5, color=NA)
```
![image](https://user-images.githubusercontent.com/757410/39146881-157bf132-4706-11e8-9110-a6b2714bbe42.png)

**Comment by hadley** [comment]
This feels out of scope for modelr to me (at a minimum, modelr needs to return standard standard errors before considering anything more sophisticated)
