### ISSUE TITLE
spread_coefficients

### ISSUE THREAD

**Issue by sjPlot** [tidyverse/modelr#21]
Additionally to `spread_predictions`, you could add a function that spreads coefficients as well. I have implemented such a function in my **sjmisc**-package:

https://github.com/sjPlot/sjmisc/blob/master/R/spread_coef.R

Maybe it fits well into the modelr-package.

**Comment by hadley** [comment]
This feels more like something that should live in broom, maybe.

**Comment by sjPlot** [comment]
Maybe, but according to the function's purpose, it comes close to the `spread*`, `add*` and `gather*` from _modelr_. And, it requires a list-variable of models, which may be created in a workflow with modelr's `bootstrap()`-function. And, `broom` mostly accepts "only" one object, which will be tidied up, or not?

Just thinking, I'm without any passion regarding in which package such a function could live. :-)

**Comment by hadley** [comment]
I now think this is out of scope for modelr, but it's something that we'll get to eventually as we integrate the ecosystem of tidy modelling packages.
