### ISSUE TITLE
Model-based bootstrap?

### ISSUE THREAD

**Issue by bgreenwell** [tidyverse/modelr#22]
I think it would be useful to have a specific method for `lm` and `nls` to perform model/residual-based bootstrap; more appropriate for data collected in such a way that the values of the predictors are held fixed (e.g., in DOEs). Perhaps by making `bootstrap` generic with methods for objects of class `data.frame`, `lm`, and `nls`--the later two would default to model-based bootstrap and would perhaps rely on `modelr::residuals`, `stats::update`, etc.?

**Comment by hadley** [comment]
More sophisticated resampling methods are outside the scope of modelr - try https://topepo.github.io/rsample/ instead
