### ISSUE TITLE
Can't specify `type` in add_predictions()

### ISSUE THREAD

**Issue by paullevchuk** [tidyverse/modelr#34]
Please, add ... to pass additional parameters to stats::predict(). 
Thanks!

**Comment by davharris** [comment]
Looks like `...` is already being used for other purposes in the prediction functions. Maybe this is a job for `.dots`?

**Comment by garrettgman** [comment]
Conspicuously, you cannot use `add_predictions()` to visualize the output of a binomial logistic regression :(
