### ISSUE TITLE
Add prediction interval to add_predictions

### ISSUE THREAD

**Issue by anhqle** [tidyverse/modelr#38]
Currently `add_predictions` does not have a way to show uncertainties about the predictions. To do that, I have to mix with `broom` as follows:

```R
m <- lm(mpg ~ disp + cyl)
d %>%
  data_grid(cyl, .model = m) %>%
  augment(m, newdata = .) %>%
  mutate(.fitted.low = .fitted - qnorm((1 - 0.9) / 2) * .se.fit,
              .fitted.low = .fitted + qnorm((1 - 0.9) / 2) * .se.fit)
```

In general, this points to some overlap between `modelr` and `broom` as both solutions to tidy model output. It's quite confusing where to go for what functionality.

**Comment by GuiMarthe** [comment]
Just to give some api design help, the expected design should follow the predict method, such as in the following snippet:

```r
library(tibble)
set.seed(1232)
df = tibble(x = rnorm(100), y = x*0.6 + rnorm(100, 0, .15))
md <- lm(y ~ x, data = df)

predict(md, list(x = 0.4), se.fit = T)

add_predictions(list(x = 0.4), md, se.fit = T)
```

**Comment by huoybb** [comment]
For api , could done by this
`m <- lm(mpg ~ disp + cyl)
d %>%
  data_grid(cyl, .model = m) %>%
  data.frame(predict(m,.,interval = "prediction")) %>%
  as.tibble()

**Comment by jebyrnes** [comment]
I added a possible solution at https://github.com/tidyverse/modelr/issues/15#issuecomment-383683831

**Comment by hadley** [comment]
The main problem is that the output of `predict()` does not have a terribly uniform interface. @topepo do you have anything lightweight that could help here?

**Comment by topepo** [comment]
> do you have anything lightweight that could help here?

Not yet. [`parsnip`](https://github.com/topepo/parsnip) will have specific predict-type functions and `pred_interval` is on the list (for models that can do this).

**Comment by jebyrnes** [comment]
Would adding dots to add_predict to pass through to the predict function of interest help?

**Comment by hadley** [comment]
Not really - I think it's the output that's more varied than the input.

**Comment by jebyrnes** [comment]
Oh, for sure - but the input in terms of accessing different intervals, etc., varies widely from package to package. At one point I wrote the following for working with lm objects:

```
add_predictions <- function (data, model, var = "pred", ...) {
  fit <- as_tibble(stats::predict(model, data, ...)$fit)
  names(fit)[1] <- var  
  bind_cols(data, fit)
}
```

which seemed to work well. However, I'm not sure how well that would extend to other model types that return a different fit column. I suppose that running predict twice - once with and once without arguments - though expensive seems like one solution. 

(Of course, then you get into the mixed model world, where packages like `merTools` supply wholly different prediction functions, but that's an obvious beyond the package scope kind of issue)

**Comment by hadley** [comment]
I think this is out of scope for modelr, since it's mostly in maintenance mode and this issue has large scope (due to the large number of models people might want)
