### ISSUE TITLE
how do you import the sim1 data?

### ISSUE THREAD

**Issue by paynito** [tidyverse/modelr#39]
Hi Hadley, I'm having trouble in section 23 "modeling" of [R for Data Science](http://r4ds.had.co.nz/model-basics.html#visualising-models)
The sim1 dataset you use in your examples isn't loading for me.

    library(tidyverse)
    library(modelr)    
    # options(na.action = na.warn)
    download.file("https://github.com/hadley/modelr/blob/master/data/sim1.rda", "sim1.rda")
    #sim1 <- readRDS("sim1.rda")
    load("sim1.rda")
    install.packages(c("nycflights13", "gapminder", "Lahman"))
    ggplot(sim1, aes(x,y))+
      geom_point()

    > load("sim1.rda")
    Error: bad restore file magic number (file may be corrupted) -- no data loaded
    In addition: Warning message:
    file ‘sim1.rda’ has magic number '<'
    Use of save versions prior to 2 is deprecated 

    Error in ggplot(sim1, aes(x, y)) : object 'sim1' not foun

**Comment by hadley** [comment]
It's included in the package

``` r
library(modelr)
sim1
#> # A tibble: 30 x 2
#>        x     y
#>    <int> <dbl>
#>  1     1  4.20
#>  2     1  7.51
#>  3     1  2.13
#>  4     2  8.99
#>  5     2 10.2 
#>  6     2 11.3 
#>  7     3  7.36
#>  8     3 10.5 
#>  9     3 10.5 
#> 10     4 12.4 
#> # ... with 20 more rows
```

Created on 2018-05-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
