### ISSUE TITLE
model_matrix does not return a matrix (or Matrix)

### ISSUE THREAD

**Issue by kaneplusplus** [tidyverse/modelr#48]
The ```model_matrix``` name is slightly confusing because it doesn't return a ```matrix``` (or ```Matrix```),  as the name suggests.

If the name ```model_tibble``` is used instead then it would be good to point out that it does include the factor expansion described by the ```formula``` argument, unlike ```model.frame```. Or, the option to include the factor expansion could be included as a argument.

**Comment by hadley** [comment]
This is confusingly named, but I think it's too late to change now 😢

**Comment by kaneplusplus** [comment]
No problem. The point is minor.
