### ISSUE TITLE
Quality metrics should support weights

### ISSUE THREAD

**Issue by kferris10** [tidyverse/modelr#50]
I would imagine that the quality metrics should support model weights.

```
library(modelr)
m <- lm(mpg ~ wt, data = mtcars, weights = hp)
rmse(m, mtcars)
[1] 3.14
sqrt(weighted.mean(residuals(m)^2, mtcars$hp))
[1] 2.83
```

I think that most standard R models return the weights so this should be straightforward.

```
names(m)
 [1] "coefficients"  "residuals"     "fitted.values" "effects"       "weights"      
 [6] "rank"          "assign"        "qr"            "df.residual"   "xlevels"      
[11] "call"          "terms"         "model"  
```

Happy to submit a PR if I'm not missing anything here.

**Comment by hadley** [comment]
I'm pretty sure that this is outside of the scope of modelr - it's a simple package designed for learning the basic ideas of modelling before you move onto more sophisticated tools like https://topepo.github.io/parsnip/
