### ISSUE TITLE
Memory waste in cross validation functions

### ISSUE THREAD

**Issue by slavakx** [tidyverse/modelr#54]
Recently we used modelr crossvalidation to build 400 models and were surprised to run out memory. We believed that the "pointer" to the dataset is a real pointer which doesn't duplicate data for each fold. 

The code of crossv_kfold and crossv_mc clearly show that the data is copied into each fold so the description of resample is highly misleading:

> Often you will resample a dataset hundreds or thousands of times. Storing the complete resample each time would be very inefficient so this class instead stores a "pointer" to the original dataset, and a vector of row indexes

**crossv_kfold**

`fold <- function(test) {`
     `list(`
        `train = resample(data, setdiff(idx, test)),`
       ` test = resample(data, test)`
        ` )`

**new crossv_kfold**

I propose a simple workaround to memory waste by passing the environment into the resample object instead of the data object itself

`env <- new.env()`
`env$data <- data`

  `fold <- function(test) {`
    `list(`
      `train = resample(env, setdiff(idx, test)),`
      `test = resample(env, test)`
   ` )`

other corresponding parts that extract data can be changed correspondignly.

**Comment by hadley** [comment]
It does not "clearly show" that the data is copied. It's certainly possible I've made a mistake but you haven't provided any compelling evidence.
