### ISSUE TITLE
Error in overscope_eval_next(overscope, expr) : object 'G' not found

### ISSUE THREAD

**Issue by taqtiqa-mark** [tidyverse/modelr#58]
Thank you for all your efforts in making these libraries available.  Much appreciated!
I believe I have found a minimal(ish) reproducible [example](https://stackoverflow.com/questions/46291976/r-tidyverse-data-grid-model-parameter#) of an issue I am also encountering.

``` r
library(tidyverse)
library(modelr)

smaller <- diamonds %>% filter(carat < 3)
mod_diamond2 <- lm(price ~ carat + color + cut + clarity, data = smaller)
grid <- smaller %>% 
  data_grid(cut, .model = mod_diamond2) %>% 
  add_predictions(mod_diamond2)
#> Error in eval_tidy(xs[[i]], unique_output): object 'G' not found
```

Created on 2018-05-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by pkq** [comment]
FWIW, I get the same error when trying to build the R for Data Science book, specifically line 127 of `model-building.Rmd` On macOS 10.12.6, R 3.4.2.

**Comment by fenghaolin** [comment]
@pkq The same happened to me, except that it was line 144 of model-building.Rmd On Windows 10, R 3.4.2.

**Comment by hughchipman** [comment]
FWIW, a specific fix to the R for Data Science book is to replace 

grid <- diamonds2 %>%                           
  data_grid(cut, .model = mod_diamond2) %>% 
  add_predictions(mod_diamond2)                  

with this:

grid <- diamonds2 %>% 
  data_grid(cut, lcarat = -0.515, color = "G", clarity = "SI1") %>% 
  add_predictions(mod_diamond2)

Basically explicitly specifying the levels of all factors that are not to be gridded.

**Comment by subaiwen** [comment]
Future question here:
How to use ```.model``` argument in ```data_grid``` ?

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(modelr)

df <- tibble::tibble(x = rep(c("a", "b"), each = 5), y = rep(c("a", "b"), 5), z = rnorm(10))
mod <- lm(z ~ x + y, data = df)
data_grid(df, .model = mod)
#> Error in eval_tidy(xs[[i]], unique_output): object 'a' not found
```

Created on 2018-05-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
