### ISSUE TITLE
Warning when using add_residuals with grouped_df

### ISSUE THREAD

**Issue by JakubKolodziej** [tidyverse/modelr#61]
Hi, 
I think that it might be worth adding a warning, when you apply add_residuals for a given model on a grouped_df. Please see an example:
`mtcars %>%  group_by(am) %>% add_residuals(lm(hp~cyl, .))`
This line does not return residuals from regressions run for each group. This model will be fitted using data in the entire data.frame. To obtain residuals from regression in each group, I need to modify this slightly to: 
 `mtcars %>%  group_by(am) %>% do(resid = add_residuals(., lm(hp ~ cyl, .)) %>% select(-am)) %>% 
   unnest(resid)`

I think that this would be consistent with the usual behaviour of mutate:
When you do this: 
`mtcars %>%  group_by(am) %>% mutate(resid = lm(hp ~ cyl, data = .)$residuals)`

At least you can expect an error (as shown below), so you know that you are not running regressions on the grouped data: 
Error in mutate_impl(.data, dots) : 
  Column `resid` must be length 19 (the group size) or one, not 32

**Comment by hadley** [comment]
I think this is based on a misunderstand of where `.` comes from - in every call _apart_ from `do()`, `.` is the whole data frame. This one of the many reasons we are generally moving away from `do()`.
